name: work
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  bloc:
  flutter_native_splash:
  smooth_page_indicator:
  hexcolor:
  curved_nav_bar:
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.6
  camera:
  sqflite:
  flutter_local_notifications:
  flutter_launcher_icons:
  google_sign_in: ^5.4.2
  currency_picker: ^2.0.13
  get: ^4.6.5
  rxdart: ^0.27.7
  share_plus: ^6.3.0
  file_picker:
  store_redirect:
  url_launcher: ^6.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_list.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

